"""Mapping of instrument names to their default LilyPond clef (treble, alto, tenor, bass)."""

_BASE_MAP: dict[str, str] = {
    # Strings - treble
    "violin": "treble",
    "violins": "treble",
    "violin i": "treble",
    "violin ii": "treble",
    "violin 1": "treble",
    "violin 2": "treble",
    "first violin": "treble",
    "second violin": "treble",
    "piccolo violin": "treble",
    "soprano violin": "treble",
    "baroque violin": "treble",
    "fiddle": "treble",
    "hardanger fiddle": "treble",
    "nyckelharpa": "treble",
    "erhu": "treble",
    "rebab": "treble",
    "sarangi": "treble",
    "kemenche": "treble",
    "kokyu": "treble",
    # Strings - alto
    "viola": "alto",
    "violas": "alto",
    "viola d'amore": "alto",
    "viola da gamba": "alto",
    "gamba": "alto",
    "treble viol": "treble",
    "tenor viol": "tenor",
    # Strings - bass
    "cello": "bass",
    "cellos": "bass",
    "violoncello": "bass",
    "baritone violin": "bass",
    "double bass": "bass",
    "contrabass": "bass",
    "bass": "bass",
    "string bass": "bass",
    "upright bass": "bass",
    "bass violin": "bass",
    "bass viol": "bass",
    "violone": "bass",
    "octobass": "bass",
    # Guitar family - treble
    "guitar": "treble",
    "acoustic guitar": "treble",
    "classical guitar": "treble",
    "nylon guitar": "treble",
    "steel string guitar": "treble",
    "electric guitar": "treble",
    "twelve-string guitar": "treble",
    "bass guitar": "bass",
    "electric bass": "bass",
    "ukulele": "treble",
    "soprano ukulele": "treble",
    "concert ukulele": "treble",
    "tenor ukulele": "treble",
    "baritone ukulele": "treble",
    "mandolin": "treble",
    "mandola": "treble",
    "mandocello": "bass",
    "lute": "treble",
    "theorbo": "bass",
    "archlute": "treble",
    "cittern": "treble",
    "balalaika": "treble",
    "domra": "treble",
    "bandurria": "treble",
    "charango": "treble",
    "bouzouki": "treble",
    "sitar": "treble",
    "tanpura": "treble",
    "oud": "treble",
    "kora": "treble",
    "banjo": "treble",
    "dobro": "treble",
    "lap steel": "treble",
    "pedal steel": "treble",
    "vihuela": "treble",
    "guitarron": "bass",
    "cuatro": "treble",
    "tres": "treble",
    "requinto": "treble",
    "ronroco": "treble",
    # Harp
    "harp": "treble",
    "celtic harp": "treble",
    "pedal harp": "treble",
    "lever harp": "treble",
    "lyre": "treble",
    # Woodwinds - flute family (treble)
    "flute": "treble",
    "flutes": "treble",
    "piccolo": "treble",
    "alto flute": "treble",
    "bass flute": "bass",
    "contrabass flute": "bass",
    "recorder": "treble",
    "soprano recorder": "treble",
    "alto recorder": "treble",
    "tenor recorder": "treble",
    "bass recorder": "bass",
    "blockflöte": "treble",
    "flageolet": "treble",
    "tin whistle": "treble",
    "penny whistle": "treble",
    "irish flute": "treble",
    "fife": "treble",
    "dizi": "treble",
    "daegeum": "treble",
    "shakuhachi": "treble",
    "quena": "treble",
    "pan flute": "treble",
    "panpipes": "treble",
    "ocarina": "treble",
    # Woodwinds - oboe family (treble)
    "oboe": "treble",
    "oboes": "treble",
    "oboe d'amore": "treble",
    "english horn": "treble",
    "cor anglais": "treble",
    "heckelphone": "treble",
    "oboe da caccia": "treble",
    "musette": "treble",
    "shenai": "treble",
    "zurna": "treble",
    "suona": "treble",
    "hichiriki": "treble",
    # Woodwinds - clarinet family
    "clarinet": "treble",
    "clarinets": "treble",
    "bb clarinet": "treble",
    "a clarinet": "treble",
    "eb clarinet": "treble",
    "soprano clarinet": "treble",
    "bass clarinet": "bass",
    "alto clarinet": "treble",
    "contrabass clarinet": "bass",
    "basset horn": "treble",
    "basset clarinet": "treble",
    "chalumeau": "treble",
    "tarogato": "treble",
    "heckelphone-clarinet": "treble",
    # Woodwinds - bassoon family (bass)
    "bassoon": "bass",
    "bassoons": "bass",
    "contrabassoon": "bass",
    "contra bassoon": "bass",
    "double bassoon": "bass",
    "tenoroon": "tenor",
    "dulcian": "bass",
    "rauschpfeife": "treble",
    "crumhorn": "treble",
    # Woodwinds - saxophone family
    "soprano saxophone": "treble",
    "soprano sax": "treble",
    "alto saxophone": "treble",
    "alto sax": "treble",
    "tenor saxophone": "treble",
    "tenor sax": "treble",
    "baritone saxophone": "bass",
    "baritone sax": "bass",
    "bass saxophone": "bass",
    "saxophone": "treble",
    "sax": "treble",
    # Woodwinds - bagpipes and folk
    "bagpipes": "treble",
    "highland pipes": "treble",
    "uilleann pipes": "treble",
    "great highland bagpipe": "treble",
    "biniou": "treble",
    "accordion": "treble",
    "concertina": "treble",
    "melodeon": "treble",
    "bandoneon": "treble",
    "harmonica": "treble",
    "harmonica (chromatic)": "treble",
    # Brass - treble
    "trumpet": "treble",
    "trumpets": "treble",
    "bb trumpet": "treble",
    "c trumpet": "treble",
    "piccolo trumpet": "treble",
    "bass trumpet": "treble",
    "cornet": "treble",
    "cornets": "treble",
    "flugelhorn": "treble",
    "pocket trumpet": "treble",
    "natural trumpet": "treble",
    "baroque trumpet": "treble",
    "serpent": "bass",
    "cornett": "treble",
    "sackbut": "bass",
    # Brass - horn
    "french horn": "treble",
    "horn": "treble",
    "horns": "treble",
    "waldhorn": "treble",
    "natural horn": "treble",
    "vienna horn": "treble",
    "wagner tuba": "bass",
    # Brass - trombone (bass/tenor)
    "trombone": "bass",
    "trombones": "bass",
    "tenor trombone": "bass",
    "bass trombone": "bass",
    "alto trombone": "alto",
    "soprano trombone": "treble",
    "contrabass trombone": "bass",
    # Brass - tuba family (bass)
    "tuba": "bass",
    "tubas": "bass",
    "bass tuba": "bass",
    "euphonium": "bass",
    "baritone": "bass",
    "baritone horn": "bass",
    "sousaphone": "bass",
    "helicon": "bass",
    "bombardon": "bass",
    "ophicleide": "bass",
    "sarrusophone": "bass",
    # Keyboards
    "piano": "treble",
    "fortepiano": "treble",
    "harpsichord": "treble",
    "clavichord": "treble",
    "virginal": "treble",
    "spinet": "treble",
    "organ": "treble",
    "pipe organ": "treble",
    "reed organ": "treble",
    "harmonium": "treble",
    "celesta": "treble",
    "clavinet": "treble",
    "synthesizer": "treble",
    "keyboard": "treble",
    "electric piano": "treble",
    # Pitched percussion
    "xylophone": "treble",
    "marimba": "treble",
    "vibraphone": "treble",
    "glockenspiel": "treble",
    "orchestral bells": "treble",
    "chimes": "treble",
    "tubular bells": "treble",
    "timpani": "bass",
    "kettledrums": "bass",
    "steelpan": "treble",
    "steel drum": "treble",
    "hang drum": "treble",
    "handpan": "treble",
    "dulcimer": "treble",
    "hammered dulcimer": "treble",
    "appalachian dulcimer": "treble",
    "cymbalom": "treble",
    "cimbalom": "treble",
    "santur": "treble",
    "yangqin": "treble",
    "kalimba": "treble",
    "thumb piano": "treble",
    "mbira": "treble",
    "tambura": "treble",
    # Voice types
    "soprano": "treble",
    "mezzo-soprano": "treble",
    "mezzo soprano": "treble",
    "alto": "alto",
    "contralto": "alto",
    "tenor": "treble",
    "baritone": "bass",
    "bass voice": "bass",
    "countertenor": "treble",
    "voice": "treble",
    "singer": "treble",
    "choir": "treble",
    "chorus": "treble",
    # Solo / generic
    "solo": "treble",
    "melody": "treble",
}

# Build extended map with numeric variations (1–100) and key variants (Bb, C, A, Eb, F, G, D)
_KEY_VARIANTS = (
    " bb", " b flat", " b-flat", " c", " a", " eb", " e flat", " e-flat",
    " f", " g", " d", " b", " f sharp", " g flat", " d flat", " a flat",
)
_INSTRUMENTS_WITH_NUMBERS = (
    "violin", "viola", "cello", "flute", "oboe", "clarinet", "bassoon", "trumpet",
    "horn", "trombone", "tuba", "saxophone", "sax", "recorder", "guitar",
    "xylophone", "marimba", "vibraphone", "timpani", "piano", "harp",
)
_ORDINALS = (
    "first", "second", "third", "fourth", "fifth", "sixth", "seventh",
    "eighth", "ninth", "tenth", "eleventh", "twelfth", "thirteenth", "fourteenth",
    "fifteenth", "sixteenth", "seventeenth", "eighteenth", "nineteenth", "twentieth",
)

INSTRUMENT_CLEF: dict[str, str] = dict(_BASE_MAP)


def _extend_map() -> None:
    for inst, clef in list(_BASE_MAP.items()):
        for key in _KEY_VARIANTS:
            if inst not in ("solo", "melody", "bass", "alto", "tenor", "baritone"):
                INSTRUMENT_CLEF[f"{inst}{key}"] = clef
    for inst in _INSTRUMENTS_WITH_NUMBERS:
        clef = _BASE_MAP.get(inst, "treble")
        for n in range(1, 201):
            INSTRUMENT_CLEF[f"{inst} {n}"] = clef
            INSTRUMENT_CLEF[f"{inst}{n}"] = clef
        for i, ord_name in enumerate(_ORDINALS, start=1):
            INSTRUMENT_CLEF[f"{inst} {ord_name}"] = clef


_extend_map()
